#!/bin/bash
APPDATA="$HOME/boincappdata"

cd "$APPDATA"
vi global_prefs_override.xml
boinccmd --host localhost:31416 --passwd "$(paste gui_rpc_auth.cfg)" --read_global_prefs_override

vi "$HOME/bin/start-boinc"
pkill start-boinc
start-boinc &
