#!/bin/sh
termux-wake-lock

renice -n 0 -p "$$" >/dev/null

# ===== User variables =====
# Working directory
APPDATA=$HOME/boincappdata.wcg

# If you have compiled BOINC yourself
BOINC_PATH=$PREFIX/bin
PATH="$BOINC_PATH:$PATH"

# Login info for boinccmd
# Set password using gui_rpc_auth.cfg
BOINC_HOST=localhost
BOINC_PORT=31416
BOINC_PASS="$(cat $APPDATA/gui_rpc_auth.cfg)"

# BOINC Android app defaults
# BATT >= 90; TEMP <= 40; AC power
# Comment/uncomment to disable/enable running at
# different power status
MIN_BATT=50
MAX_TEMP=37
PWR_STA1='PLUGGED_AC' # scale up when plugged in
#PWR_STA2='UNPLUGGED'
#PWR_STA3='PLUGGED_USB'
MIN_CPU=30
MAX_CPU=50

# ===== Script variables =====
BOINC_PORT_ARG="--gui_rpc_port $BOINC_PORT"
BOINCCMD_HOST_ARG="--host $BOINC_HOST:$BOINC_PORT"
BOINCCMD_PASS_ARG="--passwd $BOINC_PASS"
BOINCCMD_ARG="${BOINCCMD_HOST_ARG} ${BOINCCMD_PASS_ARG}"

# ===== Script functions =====
check_boinc_alive() {
    if [ -n "$(pidof -s boinc)" ] && [ -n "$(boinccmd ${BOINCCMD_ARG} --get_state 2>/dev/null)" ]; then
        BOINC_ALIVE='1'
    else
        BOINC_ALIVE=''
    fi
}

update_battery_status() {
    pkill -x main # in case termux-battery-status hangs
    pkill -x termux-api # same as above
    OLDSTAT="$STAT"
    STAT="$(timeout 5 termux-battery-status 2>/dev/null)"
    if [ -z "$(echo $STAT)" ]; then
        if [ -z "$(echo $OLDSTAT)" ]; then update_battery_status; fi
        STAT="$OLDSTAT"
    fi
    BATT="$(echo $STAT | jq .percentage)"
    PLUG="$(echo $STAT | jq .plugged | sed -e 's/"//g')"
    TEMP="$(echo $STAT | jq .temperature | sed -e 's/\..*//')"
}

check_safe_region() {
    if [ "$BATT" -gt "$MIN_BATT" ] && [ "$TEMP" -lt "$MAX_TEMP" ] && ( [ "$PLUG" = "$PWR_STA1" ] || [ "$PLUG" = "$PWR_STA2" ] || [ "$PLUG" = "$PWR_STA3" ] ); then
        SAFE_REGION='1'
    else
        SAFE_REGION=''
    fi
}

boinc_scale_up() {
    if [ "$SCALE" != 1 ]; then
        boinc-config set cpu "$MAX_CPU" >/dev/null
        SCALE=1
    fi
}

boinc_scale_down() {
    if [ "$SCALE" != 0 ]; then
        boinc-config set cpu "$MIN_CPU" >/dev/null
        SCALE=0
    fi
}

# ===== Check BOINC =====
cd "$APPDATA"
check_boinc_alive 2>/dev/null

# ===== Main script =====
sleep 10 # termux-battery-status may hang if too short
check_boinc_alive
while [ -n "$BOINC_ALIVE" ]; do
    check_boinc_alive
    update_battery_status
    check_safe_region
    if [ "$SAFE_REGION" = '1' ]; then
        boinc_scale_up
    elif [ -n "$(boinccmd --get_tasks | grep SUSPENDED)" ]; then
        true
    elif [ -n "$(boinccmd --get_tasks | grep UNINITIALIZED)" ]; then
        true
    else
        boinc_scale_down
    fi
    sleep 30 # set this lower if not responsive
done

echo 'BOINC stopped running, end of script'
