#!/bin/sh

renice -n 0 -p "$$" >/dev/null

APPDATA=${APPDATA:-$HOME/boincappdata}
BOINC_HOST=${BOINC_HOST:-localhost}
BOINC_PORT=${BOINC_PORT:-31416}
BOINC_PASS="${BOINC_PASS:-$(cat $APPDATA/gui_rpc_auth.cfg)}"
BOINC_PORT_ARG="--gui_rpc_port $BOINC_PORT"
BOINCCMD_HOST_ARG="--host $BOINC_HOST:$BOINC_PORT"
BOINCCMD_PASS_ARG="--passwd $BOINC_PASS"
BOINCCMD_ARG="${BOINCCMD_HOST_ARG} ${BOINCCMD_PASS_ARG}"
BOINC_PATH=${BOINC_PATH:-$PREFIX/bin}
PATH="$BOINC_PATH:$PATH"
STARTUP=${STARTUP:-start-boinc}

case "$1" in
edit)
	# check update-alternatives
	editor "$0" || ( echo "Error occured!" >&2 && exit 1 )
	exit
	;;
esac

cd "$APPDATA"

pkill -x main
pkill -x termux-api
echo "Current temp: $(timeout 5 termux-battery-status 2>/dev/null | jq .temperature)"
echo "Maximum temp: $(grep '^MAX_TEMP=' $(command -v $STARTUP) | sed -e 's/MAX_TEMP=//')"
echo

if [ -n "$(pidof boinc)" ]; then
	for BOINC_PID in "$(pidof boinc)"; do
		echo "BOINC PID: $BOINC_PID"
		ps -o pid,cmd --no-headers -g "$BOINC_PID" -H
	done
else
	echo 'BOINC client is not running'
fi
echo

echo 'BOINC stdoutdae.txt:'
tail stdoutdae.txt
echo

echo 'BOINC current tasks:'
boinccmd ${BOINCCMD_ARG} --get_tasks 2>&1 | \
	grep -E "   name|project URL|report deadline|active_task_state|CPU time|fraction done" | \
	sed -e "s|   ||"
