#!/data/data/com.termux/files/usr/bin/sh

renice -n 0 -p "$$" >/dev/null

APPDATA=$HOME/boincappdata
BOINC_HOST=localhost
BOINC_PORT=31416
BOINC_PASS="$(paste gui_rpc_auth.cfg)"
BOINC_PORT_ARG="--gui_rpc_port $BOINC_PORT"
BOINCCMD_HOST_ARG="--host $BOINC_HOST:$BOINC_PORT"
BOINCCMD_PASS_ARG="--passwd $BOINC_PASS"
BOINCCMD_ARG="${BOINCCMD_HOST_ARG} ${BOINCCMD_PASS_ARG}"
BOINC_PATH=$PREFIX/bin
PATH="$BOINC_PATH:$PATH"
STARTUP=start-boinc

case "$1" in
edit)
    vim "$0" || vi "$0" || nano "$0" || ( echo "Editor not found" && exit 1 )
    exit
    ;;
esac

cd "$APPDATA"

pkill -x main
pkill -x termux-api
echo "Current temp: $(termux-battery-status 2>/dev/null | jq .temperature)"
echo "Maximum temp: $(grep '^MAX_TEMP=' $(which $STARTUP) | sed 's/MAX_TEMP=//')"
echo

if [ -n "$(pidof boinc)" ]; then
    for BOINC_PID in "$(pidof boinc)"; do
        echo "BOINC PID: $BOINC_PID"
        ps -o pid,cmd --no-headers -g "$BOINC_PID" -w | sort
    done
else
    echo 'BOINC client is not running'
fi
echo

echo 'BOINC stdoutdae.txt:'
tail stdoutdae.txt
echo

echo 'BOINC current tasks:'
boinccmd ${BOINCCMD_ARG} --get_tasks 2>&1 | egrep -- '   name|active_task_state|fraction done'
